erver:
  port: 8080 # \u542F\u52A8\u7AEF\u53E3
spring:
  datasource:
    db2: # \u6570\u636E\u6E901
      jdbc-url: jdbc:mysql://127.0.0.1:3306/db2?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    db1: # \u6570\u636E\u6E902
      jdbc-url: jdbc:mysql://127.0.0.1:3306/db1?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
